from support import *
Y_model=read_array_from_txt('Results with pansim/Tests/#6/pred.txt')
U_system=read_array_from_txt('Results with pansim/Tests/#6/control.txt')
Y_real=read_array_from_txt('Results with pansim/Tests/#6/real.txt')
time=read_array_from_txt('Results with pansim/Tests/#6/execution_time.txt')
visualize_Y_quess_vs_Y_real(Y_model,Y_real,U_system)
visualize_execution_time(time)
# Y_model=read_array_from_txt('Results with pansim/Shr/#6/pred.txt')
# U_system=read_array_from_txt('Results with pansim/Shr/#6/control.txt')
# Y_real=read_array_from_txt('Results with pansim/Shr/#6/real.txt')
# visualize_Y_quess_vs_Y_real(Y_model,Y_real,U_system)
# Y_model=read_array_from_txt('neuralplant_shr_closed.txt')
# U_system=read_array_from_txt('control_shr_closed.txt')
# visualize_Y_vs_U(Y_model,U_system)
# Y_model=read_array_from_txt('Results with pansim/Closed/Shr/neuralplant_shr_closed.txt')
# U_system=read_array_from_txt('Results with pansim/Closed/Shr/control_shr_closed.txt')
# visualize_Y_vs_U(Y_model,U_system)